// `.env.ts` is generated by the `npm run env` command
// import env from './.env';

export const environment = {
  production: true,
  version: "1.0",
  serverUrl: 'http://dummy.restapiexample.com/api',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
